name: "Backend verify"

on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - 'backend/**.go'
  pull_request:
    paths:
      - 'backend/**.go'

permissions:
  contents: read

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest-4
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'backend/go.mod'
      
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: verify
        run: task backend:verify
        working-directory: backend
