---
name: Push to Buf Schema Registry
on:
  push:
    branches:
      - master
    paths:
      - proto/**.proto
  workflow_dispatch:
permissions:
  contents: read
jobs:
  push-module:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_SM_READONLY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SM_READONLY_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: get secrets from aws sm
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/buf_token
          parse-json-secrets: true
      # Run `git checkout`
      - uses: actions/checkout@v4
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      # Lint Protobuf sources
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: proto
      # Run breaking change detection for Protobuf sources against the current `main` branch
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: https://github.com/redpanda-data/console.git#branch=master,ref=HEAD~1,subdir=proto
      # Push module to the BSR
      - uses: bufbuild/buf-push-action@v1
        with:
          input: proto
          buf_token: ${{ env.BUF_TOKEN }}
          create_visibility: private
          draft: ${{ github.ref_name != 'master'}}
